### ISSUE TITLE
itunes

### ISSUE THREAD

**Issue by MMAKENPO** [LorenzoAlto/apple-website#1]
HELLO FROM GREECE!!!TELL ME PLEASE WE CAN SEARCH SONGS AND ALBUMS FROM ITUNES?AND IF YES,PLEASE COULD YOU TELL ME THE WEB?

**Comment by LorenzoAlto** [comment]
no, you can't. it is just a mockup for testing the responsiveness of the elements on the page etc..

**Comment by MMAKENPO** [comment]
oooo I see...what a pitty!!!anyway thanks so much Lorenzo!!!
